# Generated by Django 5.2.14 on 2026-05-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('ingredients', models.TextField(help_text='Ej: 2 tomates, 1 cebolla...', verbose_name='Ingredientes')),
                ('preparation', models.TextField(help_text='Pasos a seguir para cocinar.', verbose_name='Preparación')),
                ('meal_type', models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena')], max_length=20, verbose_name='Tipo de comida')),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar para que aparezca en recetas populares.', verbose_name='Destacada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
