# Generated by Django 5.2.14 on 2026-05-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('desayuno', 'Desayuno'), ('almuerzo', 'Almuerzo'), ('cena', 'Cena'), ('refrigerio_entrada', 'Refrigerios o Entradas')], max_length=20, verbose_name='Tipo de comida'),
        ),
    ]
