# Generated by Django 5.2.14 on 2026-05-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipe_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('DES', 'Desayuno'), ('ALM', 'Almuerzo'), ('CEN', 'Cena'), ('ROE', 'Refrigerios o Entradas')], max_length=3, verbose_name='Tipo de comida'),
        ),
    ]
