# Generated by Django 4.2.2 on 2026-05-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_recipe_ingredients_remove_recipe_preparation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparationstep',
            name='fase_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fase (ej: Preparación, Cocción, Montaje)'),
        ),
        migrations.AddField(
            model_name='preparationstep',
            name='show_name',
            field=models.BooleanField(default=False, verbose_name='Mostrar nombre de la fase en la receta?'),
        ),
    ]
