# Generated by Django 4.2.2 on 2026-05-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_preparationstep_fase_name_preparationstep_show_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tiempo de preparación (ej: 30 minutos)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Imagen de la receta'),
        ),
    ]
