# Generated by Django 4.2.2 on 2026-05-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_recipe_fields_and_ingredient_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.IntegerField(default=300, verbose_name='Calorías'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='portions',
            field=models.IntegerField(default=1, verbose_name='Porciones'),
        ),
    ]
