# Generated by Django 5.2.14 on 2026-07-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_recipe_calories_recipe_portions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('quantity', models.CharField(help_text='Ej: 250 g, 1 unidad, 500 ml', max_length=100, verbose_name='Cantidad')),
                ('ingredients', models.TextField(help_text='Un ingrediente por línea, o separados por coma.', verbose_name='Ingredientes')),
                ('nutritional_info', models.ImageField(blank=True, null=True, upload_to='products/nutrition/', verbose_name='Información nutricional (imagen)')),
                ('product_details', models.TextField(blank=True, verbose_name='Detalles del producto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
