# Generated by Django 5.2.14 on 2026-07-25 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Imagen')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Menor número = aparece primero. La primera es la principal.', verbose_name='Orden')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen del producto',
                'verbose_name_plural': 'Imágenes del producto',
                'ordering': ['order', 'id'],
            },
        ),
    ]
